name: Ubuntu_Server1
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: buildjet/cache@v3
    - run: source ubuntu-run.sh
    - name: Setup tmate session
      timeout-minutes: 340
      uses: mxschmitt/action-tmate@master
